logging:
  level:
    org.hibernate.SQL: "TRACE"

spring:
  application:
    name: "bookstore"

  datasource:
    url: "jdbc:sqlite:db.sqlite3"
    driver-class-name: "org.sqlite.JDBC"

  jpa:
    hibernate:
      ddl-auto: "update"

    open-in-view: false

  output:
    ansi:
      enabled: ALWAYS